### ISSUE TITLE
200+ Energy Impact on Activity Monitor

### ISSUE THREAD

**Issue by Rayrnond** [27Saumya/Macboard#10]
When using the app (just installed, didn't actually 'use' it yet), the app is using more than 200 on my Activity Monitor energy impact, which is insane. For context, 20 tabs open FireFox is using just under 300, running IntelliJ uses 150, and I personally noticed my battery go from 40% to 10% in about 30 mins, compared to normally taking 3ish hours.

<img width="966" alt="Screenshot 2024-02-22 at 5 08 59 PM" src="https://github.com/27Saumya/Macboard/assets/58085851/7ec9f7cd-da37-4b69-a0f8-f7e4277a7ecc">

**Comment by Rayrnond** [comment]
The energy impact is increasing with each "large" copy. I tested copying a large coding file (aprox. 200 lines) and it jumped from 10 to 100.

**Comment by 27Saumya** [comment]
uh-oh this shouldn't be happening, I'll look forward and release a patch soon! Also what is your macOS version

**Comment by Rayrnond** [comment]
Version 14.4 Beta (23E5205c)

**Comment by Rayrnond** [comment]
Also tested on latest stable 14.3 on a M3 MacBook Air, same issue.

**Comment by Rayrnond** [comment]
Did some instrumenting, every copy is using an interesting amount of CPU total.
<img width="1012" alt="Screenshot 2024-02-22 at 8 21 39 PM" src="https://github.com/27Saumya/Macboard/assets/58085851/de7082da-0a36-4d50-ba57-e99dc576794f">

**Comment by 27Saumya** [comment]
oh that's strange I tried replicating it on my machine, it goes max till 20, I'll check it in a while, thanks!

**Comment by 27Saumya** [comment]
oh hi @Rayrnond, I tried out it does go upto 100, but then I tried out couple other clipboard managers as well they all go upto 150 on average and even 250 quite a lot of times, the reasoning for this is:
- There isn't any `NSNotification` for `NSPasteboard` updates so we have to manually loop a task which checks for updates in the system pasteboard
- Also, this energy consumptions stays 0 whenever the app is in the background only when you open the app, it booms up and drops to 0 again as soon as you hide it, so that isn't a problem at all

### This is when the app is hidden in the menu bar
<img width="937" alt="image" src="https://github.com/27Saumya/Macboard/assets/64534496/05f7ce2b-f346-43e3-854c-5edb6ec44ff1">

### This is when the app is visible
<img width="933" alt="image" src="https://github.com/27Saumya/Macboard/assets/64534496/3ff9c347-8c2f-4455-9fcb-a65cb8ac80cf">
